### ISSUE TITLE
Make the entire book card clickable on the dashboard page.

### ISSUE THREAD

**Issue by AlexanderPuhl** [FreeCodeCamp-SLC/react-booklist#52]
![image](https://user-images.githubusercontent.com/22256166/181135400-9d0d64a1-754d-4abb-9eb4-aef114298400.png)
Currently to view the book details, you need to click on the book image. We want the entire book card outlined in red with the white background clickable.

The red list button is clickable and we want to make sure that still works.

**Comment by mcoreycoder** [comment]
I have been able to implement a red border and matched it to the booklistRed from the config. Currently, I have this set at 2px but was not sure how thick of a border was needed.

This seemed like a simple fix by wrapping the Book component in the <Link> but when trying that I received "Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>."  Which is being caused by the <HashLink> to the list.

Would we want to adhere to this warning or ignore it?

If we adhere to it then we may want to consider a slight redesign of the layout and move the <HashLink> to the bottom of the component which would allow us to have the majority of what is left wrapped in the <Link>. Look forward to hearing your thoughts.
